accounts/urls.py
# Or accounts import views / views.Home...
from django.urls import path
from accounts.views import Home
from accounts.views import SignUp
from accounts.views import Login
from accounts.views import Logout
from accounts.views import ChangePassword
from accounts.views import ChangePasswordDone
from accounts.views import ResetPassword
from accounts.views import ResetPasswordDone
from accounts.views import ResetPasswordConfirm
from accounts.views import ResetPasswordComplete

app_name = 'accounts'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('change-password/', ChangePassword.as_view(), name='change-password'),
    path('change-password-done/', ChangePasswordDone.as_view(), name='change-password-done'),
    path('reset-password/', ResetPassword.as_view(), name='reset-password'),
    path('reset-password-done/', ResetPasswordDone.as_view(), name='reset-password-done'),
    path('reset-password-confirm/<uidb64>/<token>/', ResetPasswordConfirm.as_view(), name='reset-password-confirm'),
    path('reset-password-complete/', ResetPasswordComplete.as_view(), name='reset-password-complete'),
]

djangofast/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

# Django toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(verbose_name='email', max_length=250, unique=True)

    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

USER_MODEL = get_user_model()

class CustomSignUpForm(UserCreationForm):

    class Meta:
        model = USER_MODEL
        fields = ('username', 'email', 'password1', 'password2')

class CustomAuthForm(AuthenticationForm):

    class Meta:
        model = USER_MODEL
        fields = ('username', 'password')

accounts/views.py
# Or django.contrib.auth import views / views.LoginView...
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from accounts.forms import CustomSignUpForm
from accounts.forms import CustomAuthForm
from django.urls import reverse_lazy

# Create your views here.
class Home(TemplateView):
    template_name = 'home.html'

class SignUp(CreateView):
    form_class = CustomSignUpForm
    success_url = reverse_lazy('accounts:home')
    template_name = 'signup.html'

class Login(LoginView): # Also Sign In, avoid confusion
    form_class = CustomAuthForm
    template_name = 'login.html'

class Logout(LogoutView):
    pass

class ChangePassword(PasswordChangeView):
    """
    Avoid using done view, it can be recalled instead success_url to home/profile view for example
    from django.contrib.messages.views import SuccessMessageMixin
    SuccessMessageMixin - attr: success_message = "Your password has been change"
    
    html
    {% if messages %}
        {% for message in messages %}
            <div">
                {{ message|safe }}
             </div">
        {% endfor %}
    {% endif %}

    https://docs.djangoproject.com/en/3.0/ref/contrib/messages/#adding-messages-in-class-based-views
    """
    success_url = reverse_lazy('accounts:change-password-done')
    template_name = 'change-password.html'

class ChangePasswordDone(PasswordChangeDoneView):
    template_name = 'change-password-done.html'

class ResetPassword(PasswordResetView):
    """
    Avoid using done view, it can be recalled instead success_url to home or any other view for example
    from django.contrib.messages.views import SuccessMessageMixin
    SuccessMessageMixin - attr: success_message = "We’ve emailed you instructions for setting your password"
    
    html
    {% if messages %}
        {% for message in messages %}
            <div">
                {{ message|safe }}
             </div">
        {% endfor %}
    {% endif %}

    https://docs.djangoproject.com/en/3.0/ref/contrib/messages/#adding-messages-in-class-based-views
    """
    email_template_name = 'reset-password-email.html'
    success_url = reverse_lazy('accounts:reset-password-done')
    template_name = 'reset-password.html'

class ResetPasswordDone(PasswordResetDoneView):
    template_name = 'reset-password-done.html'

class ResetPasswordConfirm(PasswordResetConfirmView):
    """
    Avoid using complete view, it can be recalled instead success_url to home or any other view for example
    from django.contrib.messages.views import SuccessMessageMixin
    SuccessMessageMixin - attr: success_message = "Your password has been set"
    
    html
    {% if messages %}
        {% for message in messages %}
            <div">
                {{ message|safe }}
             </div">
        {% endfor %}
    {% endif %}

    https://docs.djangoproject.com/en/3.0/ref/contrib/messages/#adding-messages-in-class-based-views
    """
    success_url = reverse_lazy('accounts:reset-password-complete')
    template_name = 'reset-password-confirm.html'

class ResetPasswordComplete(PasswordResetCompleteView):
    template_name = 'reset-password-complete.html'

templates/change-password-done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Your password has been change. <a href="{% url 'accounts:home' %}">Home</a></p>
    <h1>{{ message }}</h1>
</body>
</html>

templates/change-password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change">
    </form>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    {% if not user.is_authenticated %}
        <a href="{% url 'accounts:signup' %}">Sign Up</a>
        <a href="{% url 'accounts:login' %}">Log In</a>
        <a href="{% url 'accounts:reset-password' %}">Reset Password</a>
        {% else %}
        <a href="{% url 'accounts:change-password' %}">Change Password</a>
        <a href="{% url 'accounts:logout' %}">Log out</a>
    {% endif %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Log In">
    </form>
</body>
</html>

templates/reset-password-complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Complete</title>
</head>
<body>
    <p>Your password has been set.  You may go ahead and <a href="{% url 'accounts:login' %}">log in</a> now.</p>
</body>
</html>

templates/reset-password-confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password Confirm</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Reset">
    </form>
</body>
</html>

templates/reset-password-done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Done</title>
</head>
<body>
    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
</body>
</html>

templates/reset-password-email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:reset-password-confirm' uidb64=uid token=token %}

templates/reset-password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Reset">
    </form>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign Up">
    </form>
</body>
</html>